/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import capaNegocio.EAlumno;
import com.formdev.flatlaf.FlatDarculaLaf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelos.Alumno;

/**
 *
 * @author laboratorio_computo
 */
public class FrmAlumno extends javax.swing.JFrame {

    Alumno clsAlumno = new Alumno();

    EForm formActive;
    private final int id;

    /**
     * Creates new form FrmAlumno
     */
    public FrmAlumno() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);

        formActive = Module.formActive;
        id = Module.id;

        if (id == 0) {
            this.setTitle("Nuevo Ambiente");
        } else {
            this.setTitle("Editar Ambiente");

            ArrayList arrayList = clsAlumno.searchById(id);
            EAlumno alumn = (EAlumno) arrayList.get(0);
            this.txtDNI.setText(alumn.getDni());
            this.txtNombres.setText(alumn.getNombres());
            this.cboestado.setSelectedItem(alumn.getEstado());
            this.txtDireccion.setText(String.valueOf(alumn.getDireccion()));
            this.txtEmail.setText(String.valueOf(alumn.getEmail()));
            this.txtTelefono.setText(String.valueOf(alumn.getTelefono()));

            String sexo = alumn.getSexo();

            if (sexo.equalsIgnoreCase("F")) {
                this.cbosexo.setSelectedIndex(1);
            } else {
                this.cbosexo.setSelectedIndex(0);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        cbosexo = new javax.swing.JComboBox<>();
        cboestado = new javax.swing.JComboBox<>();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombres:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setText("Sexo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel4.setText("Estado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel5.setText("Dirección:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel1.setText("DNI:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel7.setText("Telefono:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 183, -1));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 183, -1));

        cbosexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cbosexo.setSelectedIndex(-1);
        jPanel1.add(cbosexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 183, -1));

        cboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        cboestado.setSelectedIndex(-1);
        jPanel1.add(cboestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 183, -1));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 183, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 183, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 183, -1));

        btnguardar.setBackground(new java.awt.Color(193, 39, 98));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("GUARDAR");
        btnguardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnguardar.setPreferredSize(new java.awt.Dimension(78, 24));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 100, 40));

        btncancelar.setBackground(new java.awt.Color(48, 48, 48));
        btncancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("CANCELAR");
        btncancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 100, 40));

        jSeparator1.setName(""); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        try {

            String nombres = this.txtNombres.getText().trim();
            String dni = this.txtDNI.getText().trim();
            String email = this.txtEmail.getText().trim();
            String telefono = this.txtTelefono.getText().trim();
            String direccion = this.txtDireccion.getText().trim();
            String estado = this.cboestado.getSelectedItem().toString();
            String sexo;

            if (cbosexo.getSelectedIndex() == 0) {
                sexo = "M";
            } else {
                sexo = "F";
            }

            if (nombres.equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese un NOMBRE", Module.titleMessage, JOptionPane.CANCEL_OPTION);
            } else {

                EAlumno objalumno = new EAlumno();
                if (id == 0) { //Registramos un nuevo rol
                    objalumno.setNombres(nombres);
                    objalumno.setDireccion(direccion);
                    objalumno.setEmail(email);
                    objalumno.setDni(dni);
                    objalumno.setSexo(sexo);
                    objalumno.setTelefono(telefono);
                    objalumno.setEstado(estado);

                    String message = clsAlumno.create(objalumno);
                    if (message.equals("Registrado correctamente")) {
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.INFORMATION_MESSAGE);
                        cleanForm();
                    } else {
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.CANCEL_OPTION);
                    }
                } else {
                    objalumno.setId(id);
                    objalumno.setNombres(nombres);
                    objalumno.setDireccion(direccion);
                    objalumno.setEmail(email);
                    objalumno.setDni(dni);
                    objalumno.setSexo(sexo);
                    objalumno.setTelefono(telefono);
                    objalumno.setEstado(estado);

                    String message = clsAlumno.update(objalumno);
                    if (message.equals("Actualizado correctamente")) {
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.INFORMATION_MESSAGE);
                        cleanForm();
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.CANCEL_OPTION);
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void cleanForm() {
        txtDNI.setText("");
        txtDireccion.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        txtNombres.setText("");
        cboestado.setSelectedIndex(-1);
        cbosexo.setSelectedIndex(-1);
        formActive.getCaller().loadTable();
        this.dispose();
    }

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        cleanForm();
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Module.id = 0;
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatDarculaLaf());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cboestado;
    private javax.swing.JComboBox<String> cbosexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
