/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import capaNegocio.EAmbiente;
import capaNegocio.EDocente;
import capaNegocio.EDeportes;
import capaNegocio.EGrupohorario;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.Ambiente;
import modelos.Deportes;
import modelos.Docente;
import modelos.Grupohorario;

/**
 *
 * @author IVAN
 */
public class Frmgrupohorario extends javax.swing.JFrame {

    Grupohorario clsGrupohorario = new Grupohorario();
    Ambiente clsAmbiente = new Ambiente();
    Docente cLsDocente = new Docente();
    Deportes clsDeportes = new Deportes();
    EForm formActive;
    private final int id;
    int id_ambiente = 0;
    int id_deporte = 0;
    int id_docente = 0;
    //int id_alumno = 0;

    private final String pattern = "yyyy-MM-dd";
    DateFormat formatter = new SimpleDateFormat(pattern);

    /**
     * Creates new form Frmgrupohorario
     */
    public Frmgrupohorario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        formActive = Module.formActive;
        id = Module.id;

        if (id == 0) {
            this.setTitle("Nuevo Ambiente");
        } else {
            this.setTitle("Editar Ambiente");

            ArrayList arrayList = clsGrupohorario.searchById(id);
            EGrupohorario grupo = (EGrupohorario) arrayList.get(0);
            this.txtnombre.setText(grupo.getNombre());
            //this.txtdeporte.setText(grupo.getDeporte());
            //this.txtdocente.setText(grupo.getDocente());
            this.txthorain.setText(String.valueOf(grupo.getHora_inicio()));
            this.txthorafin.setText(String.valueOf(grupo.getHora_fin()));
            this.cboestado.setSelectedItem(grupo.getEstado());
            //this.txtAmbiente.setText(grupo.getAmbiente());
            Module.id_deporte = grupo.getId_deporte();
            Module.id_docente = grupo.getId_docente();
            Module.id_ambiente = grupo.getId_ambiente();
            this.txtCosto.setText(grupo.getCosto()+"");
            try {
                this.jdcFechaInicio.setDate(formatter.parse(grupo.getF_inicio()));
                this.jdcFechafin.setDate(formatter.parse(grupo.getF_inicio()));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdeporte = new javax.swing.JTextField();
        btniddeporte = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtdocente = new javax.swing.JTextField();
        btniddocente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txthorain = new javax.swing.JTextField();
        txthorafin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cboestado = new javax.swing.JComboBox<>();
        txtAmbiente = new javax.swing.JTextField();
        btnidambientes = new javax.swing.JButton();
        REGISTRAR = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdcFechaInicio = new com.toedter.calendar.JDateChooser();
        jdcFechafin = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txthorain2 = new javax.swing.JTextField();
        txthorain3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 147, -1));

        jLabel8.setText("Deporte");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtdeporte.setEditable(false);
        jPanel2.add(txtdeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 150, -1));

        btniddeporte.setText("+");
        btniddeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniddeporteActionPerformed(evt);
            }
        });
        jPanel2.add(btniddeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel3.setText("Docente:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtdocente.setEditable(false);
        jPanel2.add(txtdocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 150, -1));

        btniddocente.setText("+");
        btniddocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniddocenteActionPerformed(evt);
            }
        });
        jPanel2.add(btniddocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jLabel4.setText("Fecha inicio:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setText("Fecha fin:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setText("Hora Fin:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txthorain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorainActionPerformed(evt);
            }
        });
        jPanel2.add(txthorain, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 30, -1));
        jPanel2.add(txthorafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 30, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(":");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 20, 20));

        jLabel11.setText("Hora Inicio:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        cboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jPanel2.add(cboestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 126, -1));

        txtAmbiente.setEditable(false);
        jPanel2.add(txtAmbiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 150, -1));

        btnidambientes.setText("+");
        btnidambientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidambientesActionPerformed(evt);
            }
        });
        jPanel2.add(btnidambientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        REGISTRAR.setBackground(new java.awt.Color(193, 39, 98));
        REGISTRAR.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        REGISTRAR.setForeground(new java.awt.Color(255, 255, 255));
        REGISTRAR.setText("GUARDAR");
        REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRARActionPerformed(evt);
            }
        });
        jPanel2.add(REGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, 40));

        jLabel10.setText("Estado:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel2.setText("Ambiente");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        jPanel2.add(jdcFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 150, -1));
        jPanel2.add(jdcFechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 150, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(":");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 20, 20));

        txthorain2.setEditable(false);
        txthorain2.setText("00");
        txthorain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorain2ActionPerformed(evt);
            }
        });
        jPanel2.add(txthorain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 30, -1));

        txthorain3.setEditable(false);
        txthorain3.setText("00");
        txthorain3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorain3ActionPerformed(evt);
            }
        });
        jPanel2.add(txthorain3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 30, -1));

        jLabel13.setText("Costo:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
        jPanel2.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 147, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthorainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorainActionPerformed

    private void btnidambientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidambientesActionPerformed
        FrmSeleccionarAmbientes frmsa = new FrmSeleccionarAmbientes();
        frmsa.setVisible(true);

    }//GEN-LAST:event_btnidambientesActionPerformed

    private void btniddocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniddocenteActionPerformed
        // TODO add your handling code here:
        FrmSeleccionarDocente frmDOC = new FrmSeleccionarDocente();
        frmDOC.setVisible(true);
    }//GEN-LAST:event_btniddocenteActionPerformed

    private void btniddeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniddeporteActionPerformed
        // TODO add your handling code here:
        FrmSeleccionarDeporte frmDep = new FrmSeleccionarDeporte();
        frmDep.setVisible(true);
    }//GEN-LAST:event_btniddeporteActionPerformed

    private void REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRARActionPerformed
        // TODO add your handling code here:
        try {

            String nombre = this.txtnombre.getText().trim();
            String fechaInicio = formatter.format(jdcFechaInicio.getDate());
            String fechafin = formatter.format(jdcFechafin.getDate());
            int horain = Integer.parseInt(this.txthorain.getText());
            int horafin = Integer.parseInt(this.txthorafin.getText());
            String estado = this.cboestado.getSelectedItem().toString();
            float costo = Float.parseFloat(this.txtCosto.getText());
            if (nombre.equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese un NOMBRE", Module.titleMessage, JOptionPane.CANCEL_OPTION);
            } else {

                EGrupohorario objgrupo = new EGrupohorario();
                if (id == 0) { //Registramos un nuevo rol
                    objgrupo.setNombre(nombre);
                    objgrupo.setId_deporte(id_deporte);
                    objgrupo.setId_docente(id_docente);
                    objgrupo.setF_inicio(fechaInicio);
                    objgrupo.setF_fin(fechafin);
                    objgrupo.setHora_inicio(horain);
                    objgrupo.setHora_fin(horafin);
                    objgrupo.setEstado(estado);
                    objgrupo.setId_ambiente(id_ambiente);
                    objgrupo.setCosto(costo);
                    String message = clsGrupohorario.create(objgrupo);
                    if (message.equals("Registrado correctamente")) {
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.INFORMATION_MESSAGE);
                        cleanForm();
                    } else {
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.CANCEL_OPTION);
                    }
                } else {
                    objgrupo.setId(id);
                    objgrupo.setNombre(nombre);
                    objgrupo.setId_deporte(id_deporte);
                    objgrupo.setId_docente(id_docente);
                    objgrupo.setF_inicio(fechaInicio);
                    objgrupo.setF_fin(fechafin);
                    objgrupo.setHora_inicio(horain);
                    objgrupo.setHora_fin(horafin);
                    objgrupo.setEstado(estado);
                    objgrupo.setCosto(costo);
                    objgrupo.setId_ambiente(id_ambiente);
                    String message = clsGrupohorario.update(objgrupo);
                    if (message.equals("Actualizado correctamente")) {
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.INFORMATION_MESSAGE);
                        cleanForm();
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, message, Module.titleMessage, JOptionPane.CANCEL_OPTION);
                    }
                }
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_REGISTRARActionPerformed
    private void cleanForm() {
        Module.id_ambiente = 0;
        Module.id_deporte = 0;
        Module.id_docente = 0;
        Module.id = 0;
        Module.id_gh = 0;
        txtnombre.setText("");
        txthorafin.setText("");
        txthorafin.setText("");
        txtAmbiente.setText("");
        txtdeporte.setText("");
        txtdocente.setText("");
        cboestado.setSelectedIndex(0);
        formActive.getCaller().loadTable();
        this.dispose();
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        id_ambiente = Module.id_ambiente;
        id_deporte = Module.id_deporte;
        id_docente = Module.id_docente;
        try {
            if (id_ambiente == 0) {
            } else {
                ArrayList arrayList = clsAmbiente.searchById(id_ambiente);
                EAmbiente ambient = (EAmbiente) arrayList.get(0);
                this.txtAmbiente.setText(ambient.getNombre());
            }
            if (id_deporte == 0) {
            } else {
                ArrayList arrayList2 = clsDeportes.searchById(id_deporte);
                EDeportes deport = (EDeportes) arrayList2.get(0);
                this.txtdeporte.setText(deport.getNombre());

            }
            if (id_docente == 0) {
            } else {
                ArrayList arrayList1 = cLsDocente.searchById(id_docente);
                EDocente docent = (EDocente) arrayList1.get(0);
                this.txtdocente.setText(docent.getNombres());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowActivated

    private void txthorain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorain2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorain2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        cleanForm();
    }//GEN-LAST:event_formWindowClosed

    private void txthorain3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorain3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorain3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmgrupohorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmgrupohorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmgrupohorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmgrupohorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmgrupohorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton REGISTRAR;
    private javax.swing.JButton btnidambientes;
    private javax.swing.JButton btniddeporte;
    private javax.swing.JButton btniddocente;
    private javax.swing.JComboBox<String> cboestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdcFechaInicio;
    private com.toedter.calendar.JDateChooser jdcFechafin;
    private javax.swing.JTextField txtAmbiente;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtdeporte;
    private javax.swing.JTextField txtdocente;
    private javax.swing.JTextField txthorafin;
    private javax.swing.JTextField txthorain;
    private javax.swing.JTextField txthorain2;
    private javax.swing.JTextField txthorain3;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

}
