/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package capaPresentacion;

import capaNegocio.EGrupohorario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Grupohorario;

/**
 *
 * @author an
 */
public class FrmListadoGH extends javax.swing.JInternalFrame implements IFormActive {

    DefaultTableModel defaultTable = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form FrmListadoGH
     */
    public FrmListadoGH() {
        initComponents();
        this.setResizable(false);

        this.defaultTable.addColumn("ID");
        this.defaultTable.addColumn("Nombre");
        this.defaultTable.addColumn("Deporte");
        this.defaultTable.addColumn("Docente");
        this.defaultTable.addColumn("F_Inicio");
        this.defaultTable.addColumn("F_Fin");
        this.defaultTable.addColumn("Hora inicio");
        this.defaultTable.addColumn("Hora fin");
        this.defaultTable.addColumn("Estado");
        this.defaultTable.addColumn("Ambiente");
        this.tblgrupohorario.setModel(defaultTable);
        loadTable();
    }

    @Override
    public final void loadTable() {
        try {
            for (int i = this.defaultTable.getRowCount() - 1; i >= 0; i--) {
                this.defaultTable.removeRow(i);
            }

            Grupohorario clsGrupohorario = new Grupohorario();
            ArrayList arrayList = clsGrupohorario.getAll();

            for (int i = 0; i < arrayList.size(); i++) {
                EGrupohorario dep = (EGrupohorario) arrayList.get(i);
                this.defaultTable.addRow(new Object[]{});
                this.defaultTable.setValueAt(dep.getId(), i, 0);
                this.defaultTable.setValueAt(dep.getNombre(), i, 1);
                this.defaultTable.setValueAt(dep.getDeporte(), i, 2);
                this.defaultTable.setValueAt(dep.getDocente(), i, 3);
                this.defaultTable.setValueAt(dep.getF_inicio(), i, 4);
                this.defaultTable.setValueAt(dep.getF_fin(), i, 5);
                this.defaultTable.setValueAt(dep.getHora_inicio(), i, 6);
                this.defaultTable.setValueAt(dep.getHora_fin(), i, 7);
                this.defaultTable.setValueAt(dep.getEstado(), i, 8);
                this.defaultTable.setValueAt(dep.getAmbiente(), i, 9);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), "", JOptionPane.ERROR_MESSAGE);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblgrupohorario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblgrupohorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION", "ESTADO"
            }
        ));
        tblgrupohorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblgrupohorarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblgrupohorario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1050, 660));

        jLabel1.setText("BUSCAR:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 460, 30));

        jButton1.setBackground(new java.awt.Color(193, 39, 98));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NUEVO");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblgrupohorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblgrupohorarioMouseClicked
        if (evt.getClickCount() == 2) {
            int id = (int) tblgrupohorario.getValueAt(tblgrupohorario.getSelectedRow(), 0);
            Module.id = id;
            EForm formActive = Module.formActive;
            formActive.setCaller(this);
            Frmgrupohorario formGH = new Frmgrupohorario();
            formGH.setVisible(true);
        }
    }//GEN-LAST:event_tblgrupohorarioMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        try {
            String nomString = this.txtSearch.getText().trim();
            if (nomString.equals("")) {
                loadTable();
                return;
            }

            for (int i = this.defaultTable.getRowCount() - 1; i >= 0; i--) {
                this.defaultTable.removeRow(i);
            }

            Grupohorario clsGrupohorario = new Grupohorario();
            ArrayList arrayList = clsGrupohorario.searchByName(nomString);

            for (int i = 0; i < arrayList.size(); i++) {
                EGrupohorario dep = (EGrupohorario) arrayList.get(i);
                this.defaultTable.addRow(new Object[]{});
                this.defaultTable.setValueAt(dep.getId(), i, 0);
                this.defaultTable.setValueAt(dep.getNombre(), i, 1);
                this.defaultTable.setValueAt(dep.getDeporte(), i, 2);
                this.defaultTable.setValueAt(dep.getDocente(), i, 3);
                this.defaultTable.setValueAt(dep.getF_inicio(), i, 4);
                this.defaultTable.setValueAt(dep.getF_fin(), i, 5);
                this.defaultTable.setValueAt(dep.getHora_inicio(), i, 6);
                this.defaultTable.setValueAt(dep.getHora_fin(), i, 7);
                this.defaultTable.setValueAt(dep.getEstado(), i, 8);
                this.defaultTable.setValueAt(dep.getAmbiente(), i, 9);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EForm formActive = Module.formActive;
        formActive.setCaller(this);
        Module.id = 0;
        Frmgrupohorario formGH = new Frmgrupohorario();
        formGH.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblgrupohorario;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
