/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaPresentacion;

import capaDatos.Hash;
import modelos.Login;
import capaNegocio.ELogin;
import capaNegocio.EUsuarios;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author laboratorio_computo
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        lblClickAqui = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:Iniciar Sesión");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 340, 20));
        fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 340, 20));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Alfa");
        fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Club Deportivo");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoGrande.png"))); // NOI18N
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg.jpg"))); // NOI18N
        jLabel1.setText("NOMBRE");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 300, 500));

        lblMessage.setForeground(new java.awt.Color(255, 0, 51));
        lblMessage.setText("message");
        fondo.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 340, -1));

        txtUsername.setBorder(null);
        fondo.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 340, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel6.setText("USUARIO");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        jLabel7.setText("INICIAR SESIÓN");
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel9.setText("CONTRASEÑA");
        fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        btnEntrar.setBackground(new java.awt.Color(193, 39, 98));
        btnEntrar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        fondo.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, 60));

        txtPassword.setBorder(null);
        fondo.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 340, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 90, 30));

        lblClickAqui.setText("¿No puedes iniciar sesión?");
        lblClickAqui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClickAqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClickAquiMouseClicked(evt);
            }
        });
        fondo.add(lblClickAqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
   try{
            
            Login clsLogin = new Login();
            
            lblMessage.setText("");
            String username = this.txtUsername.getText().trim();
            String password = new String(this.txtPassword.getPassword()).trim();
            
            if(username.equals("")){
                lblMessage.setText("Ingrese el usuario");
            }else if(password.equals("")){
                lblMessage.setText("Ingrese la contraseña");
            }else{
                String passwordEncrypt = Hash.encrypt(password);
                
                ELogin objLogin = new ELogin();
                objLogin.setUsername(username);
                objLogin.setPassword(passwordEncrypt);
                ArrayList arrayList = clsLogin.iniciarSesion(objLogin);
                
                if(arrayList.isEmpty()){
                    lblMessage.setText("Usuario y/o contraseña incorrecto");
                }else{
                    EUsuarios usuario = (EUsuarios)arrayList.get(0);
                    Module.userId = usuario.getId();
                    Module.userName = usuario.getNombres();
                    Module.status = usuario.getEstado();
                    Module.tipoRol = usuario.getTipoRol();
                    
                    FrmPrincipal formMenu = new FrmPrincipal();
                    formMenu.setVisible(true);
                    this.dispose();
                    
                    //JOptionPane.showMessageDialog(null, "Bienvenido: "+Module.userName, Module.titleMessage, JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString(), Module.titleMessage, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblMessage.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void lblClickAquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClickAquiMouseClicked
        // TODO add your handling code here:
        FrmEnviarCorreo formEnviarMail = new FrmEnviarCorreo();
        formEnviarMail.setVisible(true);
    }//GEN-LAST:event_lblClickAquiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblClickAqui;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
