/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package capaPresentacion;

import capaNegocio.EAlumno;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import modelos.Alumno;

/**
 *
 * @author an
 */
public class FrmListadoAlumnos extends javax.swing.JInternalFrame implements IFormActive {

    DefaultTableModel defaultTable = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form FrmListadoAlumnos
     */
    public FrmListadoAlumnos() {
        initComponents();
        //this.setLocationRelativeTo(this);
        this.setResizable(false);
        this.setTitle("Alumnos");
        this.defaultTable.addColumn("Id");
        this.defaultTable.addColumn("DNI");
        this.defaultTable.addColumn("nombre");
        this.defaultTable.addColumn("sexo");
        this.defaultTable.addColumn("Estado");
        this.defaultTable.addColumn("direccion");
        this.defaultTable.addColumn("email");
        this.defaultTable.addColumn("telefono");
        this.tblalumno.setModel(defaultTable);
        TableColumnModel columnModel = tblalumno.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(15);
        loadTable();
    }

    @Override
    public final void loadTable() {
        try {
            for (int i = this.defaultTable.getRowCount() - 1; i >= 0; i--) {
                this.defaultTable.removeRow(i);
            }

            Alumno clsAlumno = new Alumno();
            ArrayList arrayList = clsAlumno.getAll();

            for (int i = 0; i < arrayList.size(); i++) {
                EAlumno alumno = (EAlumno) arrayList.get(i);
                this.defaultTable.addRow(new Object[]{});
                this.defaultTable.setValueAt(alumno.getId(), i, 0);
                this.defaultTable.setValueAt(alumno.getDni(), i, 1);
                this.defaultTable.setValueAt(alumno.getNombres(), i, 2);
                if(alumno.getSexo().equalsIgnoreCase("M")){
                    this.defaultTable.setValueAt("Masculino", i, 3);
                }else{
                    this.defaultTable.setValueAt("Femenino", i, 3);
                }
                this.defaultTable.setValueAt(alumno.getEstado(), i, 4);
                this.defaultTable.setValueAt(alumno.getDireccion(), i, 5);
                this.defaultTable.setValueAt(alumno.getEmail(), i, 6);
                this.defaultTable.setValueAt(alumno.getTelefono(), i, 7);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), "", JOptionPane.ERROR_MESSAGE);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblalumno = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblalumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblalumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblalumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblalumno);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1050, 650));

        jLabel1.setText("BUSCAR:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 460, 30));

        jButton1.setBackground(new java.awt.Color(193, 39, 98));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NUEVO");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblalumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblalumnoMouseClicked
        if (evt.getClickCount() == 2) {
            int id = (int) tblalumno.getValueAt(tblalumno.getSelectedRow(), 0);
            Module.id = id;
            EForm formActive = Module.formActive;
            formActive.setCaller(this);
            FrmAlumno frmAlumno = new FrmAlumno();
            frmAlumno.setVisible(true);
        }
    }//GEN-LAST:event_tblalumnoMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        try {
            String nomString = this.txtSearch.getText().trim();
            if (nomString.equals("")) {
                loadTable();
                return;
            }

            for (int i = this.defaultTable.getRowCount() - 1; i >= 0; i--) {
                this.defaultTable.removeRow(i);
            }

            Alumno clsDeportes = new Alumno();
            ArrayList arrayList = clsDeportes.searchByName(nomString);

            for (int i = 0; i < arrayList.size(); i++) {
                EAlumno alumno = (EAlumno) arrayList.get(i);
                this.defaultTable.addRow(new Object[]{});
                this.defaultTable.setValueAt(alumno.getId(), i, 0);
                this.defaultTable.setValueAt(alumno.getDni(), i, 1);
                this.defaultTable.setValueAt(alumno.getNombres(), i, 2);
                if(alumno.getSexo().equalsIgnoreCase("M")){
                    this.defaultTable.setValueAt("Masculino", i, 3);
                }else{
                    this.defaultTable.setValueAt("Femenino", i, 3);
                }
                this.defaultTable.setValueAt(alumno.getEstado(), i, 4);
                this.defaultTable.setValueAt(alumno.getDireccion(), i, 5);
                this.defaultTable.setValueAt(alumno.getEmail(), i, 6);
                this.defaultTable.setValueAt(alumno.getTelefono(), i, 7);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), "", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EForm formActive = Module.formActive;
        formActive.setCaller(this);
        Module.id = 0;
        FrmAlumno frmAlumno = new FrmAlumno();
        frmAlumno.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblalumno;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
