/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package capaPresentacion;

import capaNegocio.EMatricula;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Matricula;

/**
 *
 * @author an
 */
public class FrmListadoMatriculas extends javax.swing.JInternalFrame implements IFormActive{

    DefaultTableModel defaultTable = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form FrmListadoMatriculas
     */
    public FrmListadoMatriculas() {
        initComponents();
        this.setResizable(false);

        this.defaultTable.addColumn("ID");
        this.defaultTable.addColumn("alumno");
        this.defaultTable.addColumn("grupo");
        this.defaultTable.addColumn("estado");
        this.defaultTable.addColumn("F_matricula");
        this.tblmatricula.setModel(defaultTable);
        loadTable();
    }

    @Override
    public final void loadTable() {
        try {
            for (int i = this.defaultTable.getRowCount() - 1; i >= 0; i--) {
                this.defaultTable.removeRow(i);
            }

            Matricula clsDeportes = new Matricula();
            ArrayList arrayList = clsDeportes.getAll();

            for (int i = 0; i < arrayList.size(); i++) {
                EMatricula matricula = (EMatricula) arrayList.get(i);
                this.defaultTable.addRow(new Object[]{});
                this.defaultTable.setValueAt(matricula.getId(), i, 0);
                this.defaultTable.setValueAt(matricula.getAlumno(), i, 1);
                this.defaultTable.setValueAt(matricula.getGrupo_horario(), i, 2);
                this.defaultTable.setValueAt(matricula.getEstado(), i, 3);
                this.defaultTable.setValueAt(matricula.getF_matricula(), i, 4);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), "", JOptionPane.ERROR_MESSAGE);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmatricula = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblmatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION", "ESTADO"
            }
        ));
        tblmatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmatriculaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmatricula);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1050, 660));

        jLabel1.setText("BUSCAR:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 460, 30));

        jButton1.setBackground(new java.awt.Color(193, 39, 98));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NUEVO");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblmatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmatriculaMouseClicked
        if (evt.getClickCount() == 2) {
            int id = (int) tblmatricula.getValueAt(tblmatricula.getSelectedRow(), 0);
            Module.id = id;
            EForm formActive = Module.formActive;
            formActive.setCaller(this);
            Frmmatricula formMat = new Frmmatricula();
            formMat.setVisible(true);
        }
    }//GEN-LAST:event_tblmatriculaMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        try {
            String nomString = this.txtSearch.getText().trim();
            if (nomString.equals("")) {
                loadTable();
                return;
            }

            for (int i = this.defaultTable.getRowCount() - 1; i >= 0; i--) {
                this.defaultTable.removeRow(i);
            }

            Matricula clsMatricula = new Matricula();
            ArrayList arrayList = clsMatricula.searchByName(nomString);

            for (int i = 0; i < arrayList.size(); i++) {
                EMatricula matricula = (EMatricula) arrayList.get(i);
                this.defaultTable.addRow(new Object[]{});
                this.defaultTable.setValueAt(matricula.getId(), i, 0);
                this.defaultTable.setValueAt(matricula.getAlumno(), i, 1);
                this.defaultTable.setValueAt(matricula.getGrupo_horario(), i, 2);
                this.defaultTable.setValueAt(matricula.getEstado(), i, 3);
                this.defaultTable.setValueAt(matricula.getF_matricula(), i, 4);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EForm formActive = Module.formActive;
        formActive.setCaller(this);
        Module.id = 0;   
        Frmmatricula frmmatri = new Frmmatricula();
        frmmatri.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eliminar(){
//        if (tblmatricula.getSelectedRow() < 0) {
//            JOptionPane.showMessageDialog(null, "SELECCIONE UN ELEMENTO");
//        } else {
//            try {
//                int id = (int) tblmatricula.getValueAt(tblmatricula.getSelectedRow(), 0);
//                String elemento = (String) tblmatricula.getValueAt(tblmatricula.getSelectedRow(), 1);
//                int response = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar: " + elemento + "?", "", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
//                // yes = 0, no = 1
//                if (response == 1) {
//                    txtSearch.requestFocus();
//                } else {
//                    Deportes clsDeportes = new Deportes();
//                    ArrayList arrayList = clsDeportes.searchById(id);
//                    EDeportes deporte = (EDeportes) arrayList.get(0);
//                    clsDeportes.delete(deporte);
//                    loadTable();
//                }
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, e);
//            }
//        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmatricula;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
